# 1. Create a 3x3x3 array with random values

In [17]:
import numpy as np

random_3x3x3_array = np.random.rand(3, 3, 3)

print(random_3x3x3_array)

[[[0.97885217 0.82961009 0.96322384]
  [0.61361194 0.9505957  0.71152609]
  [0.89100594 0.22052899 0.55275491]]

 [[0.77863775 0.05296896 0.4538057 ]
  [0.61517424 0.86529204 0.69775501]
  [0.62433172 0.12495266 0.78088089]]

 [[0.6329087  0.82579597 0.4240583 ]
  [0.31165242 0.46273443 0.48161991]
  [0.0805317  0.21061125 0.10036891]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [34]:
import numpy as np

diagonal_values = np.array([1, 2, 3, 4])
matrix_5x5 = np.diag(diagonal_values, k=-1)
print(matrix_5x5)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [38]:
import numpy as np

matrix = np.zeros((8, 8), dtype=int)

matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [40]:
import numpy as np

random_5x5_matrix = np.random.rand(5, 5)
normalized_matrix = (random_5x5_matrix - random_5x5_matrix.min()) / (random_5x5_matrix.max() - random_5x5_matrix.min())

print(normalized_matrix)

[[0.79283922 0.93786996 0.21313985 0.47949678 0.        ]
 [0.26020883 0.87161009 0.25557748 0.92796598 0.2565301 ]
 [0.13060354 0.39387854 0.26506229 0.09807814 0.96001434]
 [0.91986715 0.97245932 0.70413685 0.98433187 0.58051909]
 [0.50255262 0.97471663 0.47136911 1.         0.85183633]]


# 5. How to find common values between two arrays?

In [42]:
import numpy as np

array_A = np.array([1, 2, 3, 4, 5])
array_B = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array_A, array_B)

print(common_values)

[3 4 5]


# 6.How to get the dates of yesterday, today and tomorrow?

In [43]:
from datetime import datetime, timedelta

today = datetime.now()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print(f"Yesterday: {yesterday.strftime('%Y-%m-%d')}")
print(f"Today: {today.strftime('%Y-%m-%d')}")
print(f"Tomorrow: {tomorrow.strftime('%Y-%m-%d')}")

Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [47]:
import numpy as np

array_A = np.array([1, 2, 3, 4, 5])
array_B = np.array([1, 2, 3, 4, 5])

are_equal = np.array_equal(array_A, array_B)

print(are_equal)

True


# 8.Create random vector of size 10 and replace the maximum value by 0

In [18]:
import numpy as np

random_vector = np.random.rand(10)

max_index = np.argmax(random_vector)

random_vector[max_index] = 0

print("Random Vector with Maximum Value Replaced: \n", random_vector)

Random Vector with Maximum Value Replaced: 
 [0.35437183 0.25922274 0.92427332 0.34992979 0.27238123 0.54735299
 0.33627482 0.30338133 0.81699556 0.        ]


# 9. How to print all the values of an array?

In [19]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])

for value in my_array:
    print(value)


1
2
3
4
5


# 10. Subtract the mean of each row of a matrix

In [20]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_means = np.mean(matrix, axis=1, keepdims=True)

result_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)

print("\nMatrix with Row Means Subtracted:")
print(result_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [21]:
import numpy as np

given_vector = np.array([1, 2, 3, 4, 5])

indices_to_add_1 = np.array([1, 3, 3, 4])

mask = np.zeros_like(given_vector, dtype=bool)

mask[indices_to_add_1] = True

given_vector[mask] += 1

print("Given Vector:")
print(given_vector)


Given Vector:
[1 3 3 5 6]


# 12.How to get the diagonal of a dot product?

In [22]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

dot_product = np.dot(matrix1, matrix2)

diagonal = np.diag(dot_product)

print("\nMatrix1:")
print(matrix1)

print("\nMatrix2:")
print(matrix2)

print("\nDot Product Matrix:")
print(dot_product)

print("\nDiagonal of the Dot Product:")
print(diagonal)


Matrix1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Dot Product Matrix:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of the Dot Product:
[30 69 90]


# 13.How to find the most frequent value in an array?

In [23]:
import numpy as np

arr = np.array([2, 3, 2, 5, 8, 2, 3, 7, 8, 8, 3])

unique_values, counts = np.unique(arr, return_counts=True)

max_count = np.max(counts)

max_count_indices = np.where(counts == max_count)

most_frequent_values = unique_values[max_count_indices]

print("Array:")
print(arr)

print("Most Frequent Value(s):", most_frequent_values)

Array:
[2 3 2 5 8 2 3 7 8 8 3]
Most Frequent Value(s): [2 3 8]


# 14.How to get the n largest value in the array.

In [25]:
import heapq

def get_n_largest(arr, n):
    return heapq.nlargest(n, arr)

my_array = [12, 34, 45, 9, 8, 76]
n = 1
n_largest_values = get_n_largest(my_array, n)
print(n_largest_values)

[76]


# 15.How to create a record array from a regular array.

In [29]:
import numpy as np

regular_array = [(1, "Alice", 25), (2, "Bob", 30), (3, "Charlie", 22)]

dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]

record_array = np.array(regular_array, dtype=dtype)

print("First record:")
print("ID:", record_array[0]['ID'])
print("Name:", record_array[0]['Name'])
print("Age:", record_array[0]['Age'])

print("\nSecond record:")
print("ID:", record_array[1][0])
print("Name:", record_array[1][1])
print("Age:", record_array[1][2])

First record:
ID: 1
Name: Alice
Age: 25

Second record:
ID: 2
Name: Bob
Age: 30


# 16.How to swap two rows of an array.

In [30]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

row1_index = 0
row2_index = 2

temp_row = np.copy(array[row1_index])
array[row1_index] = array[row2_index]
array[row2_index] = temp_row

print(array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17.Write python code to reshape  to the next dimenssion of numpy array.

In [32]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = original_array.reshape((2, -1))

print("Original array:")
print(original_array)
print("Reshaped array:")
print(reshaped_array)

Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]
